checks:
    php: true

filter:
    paths:
        - 'avatar-privacy.php'
        - 'admin/'
        - 'public/'
        - 'includes/'
    dependency_paths:
        - wordpress/
        - tests/phpstan/

build:
    cache:
        directories:
            - ~/.composer   # Composer home directory (avoid fetching already fetched packages)
            # vendor is already included.
    environment:
        rabbitmq: false
        mysql: false
        postgresql: false
        mongodb: false
        elasticsearch: false
        redis: false
        memcached: false
        neo4j: false
        php:
            version: 7.4

    nodes:
        analysis:
            project_setup:
                override: true
            dependencies:
                before:
                    - composer require --dev johnpbloch/wordpress-core
                    - composer require --dev wp-cli/wp-cli
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis
                    - phpcs-run --standard=phpcs.xml avatar-privacy.php uninstall.php admin/ public/ includes/ --extensions=php

tools:
    php_code_sniffer: false
    php_cs_fixer: false
    external_code_coverage: true
